#!/usr/bin/env bash
# ============================================================================
# generate-brewfile-current.sh
# ============================================================================
# Generates Brewfile.current by checking what's already installed
# Checks: brew database, system binaries, cargo, npm, etc.
# 
# Usage:
#   ./scripts/generate-brewfile-current.sh
#   brew bundle --file=Brewfile.current
# ============================================================================

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
DOTFILES_DIR="$(dirname "$SCRIPT_DIR")"
SUPERSET_FILE="$DOTFILES_DIR/Brewfile.superset"
OUTPUT_FILE="$DOTFILES_DIR/Brewfile.current"

# Colors for output
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
NC='\033[0m' # No Color

# ============================================================================
# Helper Functions
# ============================================================================

log_info() {
    echo -e "${BLUE}ℹ${NC} $1"
}

log_success() {
    echo -e "${GREEN}✓${NC} $1"
}

log_warning() {
    echo -e "${YELLOW}⚠${NC} $1"
}

log_error() {
    echo -e "${RED}✗${NC} $1"
}

# Check if a formula is installed via brew
is_brew_formula_installed() {
    local formula="$1"
    brew list --formula 2>/dev/null | grep -q "^${formula}$"
}

# Check if a cask is installed via brew
is_brew_cask_installed() {
    local cask="$1"
    brew list --cask 2>/dev/null | grep -q "^${cask}$"
}

# Check if a binary exists in PATH
is_binary_available() {
    local binary="$1"
    command -v "$binary" &>/dev/null
}

# Check if a cargo package is installed
is_cargo_installed() {
    local package="$1"
    cargo install --list 2>/dev/null | grep -q "^${package} "
}

# Extract package name from brew line (handles quotes and comments)
extract_package_name() {
    local line="$1"
    echo "$line" | sed -E 's/^[^"]*"([^"]+)".*/\1/'
}

# Determine if a brew formula should be skipped
should_skip_formula() {
    local formula="$1"
    local binary="${2:-$formula}"  # Default binary name = formula name
    
    # Check brew first
    if is_brew_formula_installed "$formula"; then
        echo "brew"
        return 0
    fi
    
    # Check if binary exists in PATH
    if is_binary_available "$binary"; then
        echo "system"
        return 0
    fi
    
    # Special case: check cargo for Rust tools
    case "$formula" in
        bat|eza|fd|ripgrep|sd|procs|bottom|dust|tokei|hyperfine|zoxide|starship)
            if is_cargo_installed "$formula"; then
                echo "cargo"
                return 0
            fi
            ;;
    esac
    
    return 1
}

# Determine if a cask should be skipped
should_skip_cask() {
    local cask="$1"
    
    # Check brew cask first
    if is_brew_cask_installed "$cask"; then
        echo "brew"
        return 0
    fi
    
    # Check for common app locations
    case "$cask" in
        iterm2)
            [ -d "/Applications/iTerm.app" ] && echo "system" && return 0
            ;;
        visual-studio-code)
            [ -d "/Applications/Visual Studio Code.app" ] && echo "system" && return 0
            ;;
        docker)
            if is_binary_available "docker"; then
                echo "system"
                return 0
            fi
            ;;
        rectangle)
            [ -d "/Applications/Rectangle.app" ] && echo "system" && return 0
            ;;
        alfred)
            [ -d "/Applications/Alfred 5.app" ] || [ -d "/Applications/Alfred 4.app" ] && echo "system" && return 0
            ;;
        obsidian)
            [ -d "/Applications/Obsidian.app" ] && echo "system" && return 0
            ;;
    esac
    
    return 1
}

# ============================================================================
# Main Processing
# ============================================================================

main() {
    log_info "Generating Brewfile.current from Brewfile.superset..."
    echo ""
    
    if [ ! -f "$SUPERSET_FILE" ]; then
        log_error "Brewfile.superset not found at: $SUPERSET_FILE"
        exit 1
    fi
    
    # Create header
    cat > "$OUTPUT_FILE" << EOF
# ============================================================================
# Brewfile.current - AUTO-GENERATED
# ============================================================================
# Generated by: scripts/generate-brewfile-current.sh
# Date: $(date)
#
# This file contains only packages NOT already installed on this system.
# Checked: brew database, system binaries, cargo packages, app bundles
# ============================================================================

EOF
    
    local total_lines=0
    local skipped_brew=0
    local skipped_system=0
    local skipped_cargo=0
    local included=0
    
    # Process each line from superset
    while IFS= read -r line || [ -n "$line" ]; do
        total_lines=$((total_lines + 1))

        # Pass through comments and empty lines
        if [[ "$line" =~ ^[[:space:]]*# ]] || [[ -z "$line" ]]; then
            echo "$line" >> "$OUTPUT_FILE"
            continue
        fi
        
        # Pass through tap lines
        if [[ "$line" =~ ^tap ]]; then
            echo "$line" >> "$OUTPUT_FILE"
            continue
        fi
        
        # Handle brew formulas
        if [[ "$line" =~ ^brew ]]; then
            local formula=$(extract_package_name "$line")
            local skip_reason=""
            
            if skip_reason=$(should_skip_formula "$formula"); then
                echo "# SKIP ($skip_reason): $line" >> "$OUTPUT_FILE"
                case "$skip_reason" in
                    brew) skipped_brew=$((skipped_brew + 1)) ;;
                    system) skipped_system=$((skipped_system + 1)) ;;
                    cargo) skipped_cargo=$((skipped_cargo + 1)) ;;
                esac
                log_warning "Skipping formula: $formula ($skip_reason)"
            else
                echo "$line" >> "$OUTPUT_FILE"
                included=$((included + 1))
                log_success "Including formula: $formula"
            fi
            continue
        fi
        
        # Handle casks
        if [[ "$line" =~ ^cask ]]; then
            local cask=$(extract_package_name "$line")
            local skip_reason=""
            
            if skip_reason=$(should_skip_cask "$cask"); then
                echo "# SKIP ($skip_reason): $line" >> "$OUTPUT_FILE"
                case "$skip_reason" in
                    brew) skipped_brew=$((skipped_brew + 1)) ;;
                    system) skipped_system=$((skipped_system + 1)) ;;
                esac
                log_warning "Skipping cask: $cask ($skip_reason)"
            else
                echo "$line" >> "$OUTPUT_FILE"
                included=$((included + 1))
                log_success "Including cask: $cask"
            fi
            continue
        fi
        
        # Pass through anything else
        echo "$line" >> "$OUTPUT_FILE"
        
    done < "$SUPERSET_FILE"
    
    # Summary
    echo ""
    log_info "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
    log_success "Generated: $OUTPUT_FILE"
    echo ""
    echo "  📊 Summary:"
    echo "     Total packages checked: $((skipped_brew + skipped_system + skipped_cargo + included))"
    echo "     ${GREEN}✓${NC} To install: $included"
    echo "     ${YELLOW}⊘${NC} Skipped (brew): $skipped_brew"
    echo "     ${YELLOW}⊘${NC} Skipped (system): $skipped_system"
    echo "     ${YELLOW}⊘${NC} Skipped (cargo): $skipped_cargo"
    echo ""
    log_info "Next steps:"
    echo "  1. Review: cat Brewfile.current"
    echo "  2. Install: brew bundle --file=Brewfile.current"
    log_info "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
}

main "$@"

